// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wirex

import (
	"context"
	"github.com/yanzongzhen/magnetu/internal/mods"
	"github.com/yanzongzhen/magnetu/internal/mods/rbac"
	"github.com/yanzongzhen/magnetu/internal/mods/rbac/api"
	"github.com/yanzongzhen/magnetu/internal/mods/rbac/biz"
	"github.com/yanzongzhen/magnetu/internal/mods/rbac/dal"
	"github.com/yanzongzhen/magnetu/internal/mods/repository"
	api3 "github.com/yanzongzhen/magnetu/internal/mods/repository/api"
	biz3 "github.com/yanzongzhen/magnetu/internal/mods/repository/biz"
	dal3 "github.com/yanzongzhen/magnetu/internal/mods/repository/dal"
	"github.com/yanzongzhen/magnetu/internal/mods/sys"
	api2 "github.com/yanzongzhen/magnetu/internal/mods/sys/api"
	biz2 "github.com/yanzongzhen/magnetu/internal/mods/sys/biz"
	dal2 "github.com/yanzongzhen/magnetu/internal/mods/sys/dal"
	"github.com/yanzongzhen/magnetu/pkg/util"
)

// Injectors from wire.go:

func BuildInjector(ctx context.Context) (*Injector, func(), error) {
	db, cleanup, err := InitDB(ctx)
	if err != nil {
		return nil, nil, err
	}
	cacher, cleanup2, err := InitCacher(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	auther, cleanup3, err := InitAuth(ctx)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	trans := &util.Trans{
		DB: db,
	}
	menu := &dal.Menu{
		DB: db,
	}
	menuResource := &dal.MenuResource{
		DB: db,
	}
	roleMenu := &dal.RoleMenu{
		DB: db,
	}
	bizMenu := &biz.Menu{
		Trans:           trans,
		MenuDAL:         menu,
		MenuResourceDAL: menuResource,
		RoleMenuDAL:     roleMenu,
	}
	apiMenu := &api.Menu{
		MenuBIZ: bizMenu,
	}
	role := &dal.Role{
		DB: db,
	}
	userRole := &dal.UserRole{
		DB: db,
	}
	bizRole := &biz.Role{
		Cache:       cacher,
		Trans:       trans,
		RoleDAL:     role,
		RoleMenuDAL: roleMenu,
		UserRoleDAL: userRole,
	}
	apiRole := &api.Role{
		RoleBIZ: bizRole,
	}
	user := &dal.User{
		DB: db,
	}
	bizUser := &biz.User{
		Cache:       cacher,
		Trans:       trans,
		UserDAL:     user,
		UserRoleDAL: userRole,
	}
	apiUser := &api.User{
		UserBIZ: bizUser,
	}
	login := &biz.Login{
		Cache:       cacher,
		Auth:        auther,
		UserDAL:     user,
		UserRoleDAL: userRole,
		MenuDAL:     menu,
		UserBIZ:     bizUser,
	}
	apiLogin := &api.Login{
		LoginBIZ: login,
	}
	casbinx := &rbac.Casbinx{
		Cache:           cacher,
		MenuDAL:         menu,
		MenuResourceDAL: menuResource,
		RoleDAL:         role,
	}
	rbacRBAC := &rbac.RBAC{
		DB:       db,
		MenuAPI:  apiMenu,
		RoleAPI:  apiRole,
		UserAPI:  apiUser,
		LoginAPI: apiLogin,
		Casbinx:  casbinx,
	}
	logger := &dal2.Logger{
		DB: db,
	}
	bizLogger := &biz2.Logger{
		LoggerDAL: logger,
	}
	apiLogger := &api2.Logger{
		LoggerBIZ: bizLogger,
	}
	sysSYS := &sys.SYS{
		DB:        db,
		LoggerAPI: apiLogger,
	}
	dalRepository := &dal3.Repository{
		DB: db,
	}
	bizRepository := &biz3.Repository{
		Trans:         trans,
		RepositoryDAL: dalRepository,
	}
	apiRepository := &api3.Repository{
		RepositoryBIZ: bizRepository,
	}
	folder := &dal3.Folder{
		DB: db,
	}
	bizFolder := &biz3.Folder{
		Trans:     trans,
		FolderDAL: folder,
	}
	apiFolder := &api3.Folder{
		FolderBIZ: bizFolder,
	}
	file := &dal3.File{
		DB: db,
	}
	bizFile := &biz3.File{
		Trans:   trans,
		FileDAL: file,
	}
	apiFile := &api3.File{
		FileBIZ: bizFile,
	}
	repositoryRepository := &repository.Repository{
		DB:            db,
		RepositoryAPI: apiRepository,
		FolderAPI:     apiFolder,
		FileAPI:       apiFile,
	}
	modsMods := &mods.Mods{
		RBAC:       rbacRBAC,
		SYS:        sysSYS,
		Repository: repositoryRepository,
	}
	injector := &Injector{
		DB:    db,
		Cache: cacher,
		Auth:  auther,
		M:     modsMods,
	}
	return injector, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
